---
abstract: 'perl extension to talk to FTDI chips'
author:
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::PkgConfig: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-FTDI
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
resources:
  bugtracker: https://github.com/trinitum/perl-Device-FTDI/issues
  homepage: https://github.com/trinitum/perl-Device-FTDI
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/perl-Device-FTDI
version: 0.04
